'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { generateShadowName } from '@/lib/utils/identity';

interface IdentitySetupWizardProps {
  userId: string;
  onComplete?: () => void;
}

type Step = 1 | 2 | 3 | 4;

export function IdentitySetupWizard({ userId, onComplete }: IdentitySetupWizardProps) {
  const router = useRouter();
  const { setupIdentity, user } = useAuth();

  const [currentStep, setCurrentStep] = useState<Step>(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [trueSelfData, setTrueSelfData] = useState({
    displayName: '',
    bio: '',
    avatarUrl: '',
  });

  const [shadowData, setShadowData] = useState({
    useAutoGenerated: true,
    customName: '',
  });

  const [understood, setUnderstood] = useState(false);

  // Generate preview shadow name
  const previewShadowName = shadowData.useAutoGenerated
    ? generateShadowName(userId)
    : shadowData.customName;

  const handleNext = () => {
    setError(null);

    if (currentStep === 1) {
      if (!understood) {
        setError('Please confirm that you understand the dual-identity system');
        return;
      }
    }

    if (currentStep === 2) {
      if (!trueSelfData.displayName.trim()) {
        setError('Please enter a display name for your True Self');
        return;
      }
    }

    if (currentStep < 4) {
      setCurrentStep((currentStep + 1) as Step);
    }
  };

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep((currentStep - 1) as Step);
    }
  };

  const handleComplete = async () => {
    setLoading(true);
    setError(null);

    try {
      await setupIdentity({
        trueSelf: {
          displayName: trueSelfData.displayName,
          bio: trueSelfData.bio || undefined,
          avatarUrl: trueSelfData.avatarUrl || undefined,
        },
        shadow: {
          useAutoGenerated: shadowData.useAutoGenerated,
          customName: shadowData.useAutoGenerated ? undefined : shadowData.customName,
        },
      });

      // Move to final step
      setCurrentStep(4);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Setup failed');
    } finally {
      setLoading(false);
    }
  };

  const handleGoToDashboard = () => {
    if (onComplete) {
      onComplete();
    } else {
      router.push('/dashboard');
    }
  };

  return (
    <Card className="w-full max-w-2xl">
      <CardHeader>
        <div className="flex items-center justify-between mb-2">
          <div className="text-sm text-gray-500">
            Step {currentStep} of 4
          </div>
          <div className="flex space-x-2">
            {[1, 2, 3, 4].map((step) => (
              <div
                key={step}
                className={`h-2 w-8 rounded-full ${
                  step <= currentStep ? 'bg-blue-600' : 'bg-gray-200'
                }`}
              />
            ))}
          </div>
        </div>

        {currentStep === 1 && (
          <>
            <CardTitle>Understanding Dual Identity</CardTitle>
            <CardDescription>
              Learn about True Self and Shadow modes
            </CardDescription>
          </>
        )}
        {currentStep === 2 && (
          <>
            <CardTitle>Create Your True Self</CardTitle>
            <CardDescription>
              Your public identity for open discussion
            </CardDescription>
          </>
        )}
        {currentStep === 3 && (
          <>
            <CardTitle>Create Your Shadow</CardTitle>
            <CardDescription>
              Your private identity for anonymous participation
            </CardDescription>
          </>
        )}
        {currentStep === 4 && (
          <>
            <CardTitle>Setup Complete!</CardTitle>
            <CardDescription>
              Your dual identities are ready
            </CardDescription>
          </>
        )}
      </CardHeader>

      <CardContent className="space-y-6">
        {error && (
          <div className="rounded-md bg-red-50 p-3 text-sm text-red-800 border border-red-200">
            {error}
          </div>
        )}

        {/* Step 1: Explanation */}
        {currentStep === 1 && (
          <div className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-4 border-2 border-blue-200 rounded-lg bg-blue-50">
                <div className="text-2xl mb-2">👤</div>
                <h3 className="font-semibold text-blue-900 mb-2">True Self</h3>
                <p className="text-sm text-blue-800">
                  Your public identity. Use this when you want to take credit for your ideas
                  and build your reputation in the community.
                </p>
              </div>

              <div className="p-4 border-2 border-purple-200 rounded-lg bg-purple-50">
                <div className="text-2xl mb-2">🎭</div>
                <h3 className="font-semibold text-purple-900 mb-2">Shadow</h3>
                <p className="text-sm text-purple-800">
                  Your anonymous identity. Use this when you want to speak freely without
                  social pressure or judgment.
                </p>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
              <h4 className="font-semibold mb-2">Why Dual Identity?</h4>
              <ul className="space-y-2 text-sm text-gray-700">
                <li className="flex items-start">
                  <span className="mr-2">✓</span>
                  <span>Speak truth without fear of social consequences</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">✓</span>
                  <span>Discover the gap between public opinion and private beliefs</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">✓</span>
                  <span>Build reputation while maintaining privacy when needed</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">✓</span>
                  <span>Switch between identities anytime</span>
                </li>
              </ul>
            </div>

            <div className="flex items-start space-x-2 bg-yellow-50 p-3 rounded-lg border border-yellow-200">
              <input
                id="understood"
                type="checkbox"
                checked={understood}
                onChange={(e) => setUnderstood(e.target.checked)}
                className="mt-1 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
              />
              <Label htmlFor="understood" className="text-sm font-normal cursor-pointer text-yellow-900">
                I understand that I will have two separate identities, and content created
                in one mode cannot be accessed in the other mode.
              </Label>
            </div>
          </div>
        )}

        {/* Step 2: True Self Setup */}
        {currentStep === 2 && (
          <div className="space-y-4">
            <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
              <div className="flex items-center space-x-2 mb-2">
                <span className="text-2xl">👤</span>
                <h3 className="font-semibold text-blue-900">True Self Profile</h3>
              </div>
              <p className="text-sm text-blue-800">
                This is your public identity. This information will be visible to all users.
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="displayName">Display Name *</Label>
              <Input
                id="displayName"
                type="text"
                placeholder="How should we call you?"
                value={trueSelfData.displayName}
                onChange={(e) =>
                  setTrueSelfData({ ...trueSelfData, displayName: e.target.value })
                }
                required
              />
              <p className="text-xs text-gray-500">
                This is how other users will see you in True Self mode
              </p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="bio">Bio (Optional)</Label>
              <textarea
                id="bio"
                className="flex min-h-[80px] w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:cursor-not-allowed disabled:opacity-50"
                placeholder="Tell us about yourself..."
                value={trueSelfData.bio}
                onChange={(e) =>
                  setTrueSelfData({ ...trueSelfData, bio: e.target.value })
                }
                maxLength={500}
              />
              <p className="text-xs text-gray-500">
                {trueSelfData.bio.length}/500 characters
              </p>
            </div>
          </div>
        )}

        {/* Step 3: Shadow Setup */}
        {currentStep === 3 && (
          <div className="space-y-4">
            <div className="bg-purple-50 p-4 rounded-lg border border-purple-200">
              <div className="flex items-center space-x-2 mb-2">
                <span className="text-2xl">🎭</span>
                <h3 className="font-semibold text-purple-900">Shadow Profile</h3>
              </div>
              <p className="text-sm text-purple-800">
                Your anonymous identity. No personal information will be attached to this profile.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex items-start space-x-2">
                <input
                  id="autoGenerated"
                  type="radio"
                  checked={shadowData.useAutoGenerated}
                  onChange={() =>
                    setShadowData({ ...shadowData, useAutoGenerated: true })
                  }
                  className="mt-1"
                />
                <Label htmlFor="autoGenerated" className="font-normal cursor-pointer">
                  <div className="font-medium">Use auto-generated name (Recommended)</div>
                  <div className="text-sm text-gray-500">
                    We'll create a unique anonymous name for you
                  </div>
                  {shadowData.useAutoGenerated && (
                    <div className="mt-2 p-2 bg-white rounded border border-purple-200">
                      <span className="text-sm font-medium">Preview: </span>
                      <span className="text-sm text-purple-700">{previewShadowName}</span>
                    </div>
                  )}
                </Label>
              </div>

              <div className="flex items-start space-x-2">
                <input
                  id="customName"
                  type="radio"
                  checked={!shadowData.useAutoGenerated}
                  onChange={() =>
                    setShadowData({ ...shadowData, useAutoGenerated: false })
                  }
                  className="mt-1"
                />
                <Label htmlFor="customName" className="font-normal cursor-pointer flex-1">
                  <div className="font-medium">Choose my own anonymous name</div>
                  <div className="text-sm text-gray-500 mb-2">
                    Pick a name that doesn't reveal your identity
                  </div>
                  {!shadowData.useAutoGenerated && (
                    <Input
                      type="text"
                      placeholder="Enter anonymous name"
                      value={shadowData.customName}
                      onChange={(e) =>
                        setShadowData({ ...shadowData, customName: e.target.value })
                      }
                    />
                  )}
                </Label>
              </div>
            </div>

            <div className="bg-yellow-50 p-3 rounded-lg border border-yellow-200 text-sm text-yellow-900">
              <strong>Privacy Note:</strong> Your Shadow identity is completely separate from
              your True Self. No one will know these identities belong to the same person.
            </div>
          </div>
        )}

        {/* Step 4: Success */}
        {currentStep === 4 && (
          <div className="space-y-6">
            <div className="text-center py-8">
              <div className="text-6xl mb-4">🎉</div>
              <h3 className="text-2xl font-bold text-gray-900 mb-2">
                You're All Set!
              </h3>
              <p className="text-gray-600">
                Your dual identities have been created successfully
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-4 border-2 border-blue-200 rounded-lg bg-blue-50">
                <div className="text-2xl mb-2">👤</div>
                <h4 className="font-semibold text-blue-900">True Self</h4>
                <p className="text-sm text-blue-800 mt-1">
                  {trueSelfData.displayName}
                </p>
                {user?.wallets?.trueSelf && (
                  <p className="text-xs text-blue-600 mt-2 font-mono">
                    Wallet: {user.wallets.trueSelf.substring(0, 12)}...
                  </p>
                )}
              </div>

              <div className="p-4 border-2 border-purple-200 rounded-lg bg-purple-50">
                <div className="text-2xl mb-2">🎭</div>
                <h4 className="font-semibold text-purple-900">Shadow</h4>
                <p className="text-sm text-purple-800 mt-1">
                  {previewShadowName}
                </p>
                {user?.wallets?.shadow && (
                  <p className="text-xs text-purple-600 mt-2 font-mono">
                    Wallet: {user.wallets.shadow.substring(0, 12)}...
                  </p>
                )}
              </div>
            </div>

            <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
              <h4 className="font-semibold text-blue-900 mb-2">Next Steps:</h4>
              <ul className="space-y-2 text-sm text-blue-800">
                <li className="flex items-start">
                  <span className="mr-2">1.</span>
                  <span>Explore the platform and familiarize yourself with the interface</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">2.</span>
                  <span>Participate in polls and discussions</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">3.</span>
                  <span>Try switching between True Self and Shadow modes</span>
                </li>
                <li className="flex items-start">
                  <span className="mr-2">4.</span>
                  <span>Build your Light Score through meaningful contributions</span>
                </li>
              </ul>
            </div>
          </div>
        )}
      </CardContent>

      <CardFooter className="flex justify-between">
        {currentStep !== 4 && (
          <>
            <Button
              variant="outline"
              onClick={handleBack}
              disabled={currentStep === 1 || loading}
            >
              Back
            </Button>

            {currentStep < 3 ? (
              <Button onClick={handleNext} disabled={loading}>
                Next
              </Button>
            ) : (
              <Button onClick={handleComplete} disabled={loading}>
                {loading ? 'Creating...' : 'Complete Setup'}
              </Button>
            )}
          </>
        )}

        {currentStep === 4 && (
          <Button onClick={handleGoToDashboard} className="w-full">
            Go to Dashboard
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}