/**
 * Dream Protocol API Types
 * Enhanced types for dual-identity system
 */

// ============================================
// Core Types
// ============================================

export type IdentityMode = 'true_self' | 'shadow';

export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

// ============================================
// User & Identity Types
// ============================================

export interface User {
  id: string;                    // Internal user ID
  identity: string;              // Active identity (userId or shadowHash)
  username?: string;             // Only in true_self mode
  email?: string;                // Only in true_self mode
  mode: IdentityMode;            // Current identity mode

  // Profile data
  profile?: UserProfile;

  // Dream Protocol specific
  lightScore?: number;           // Reputation (0-100)
  wallets?: {
    trueSelf?: string;           // Cardano wallet address
    shadow?: string;             // Shadow wallet address
  };
  did?: string;                  // Decentralized Identifier

  // Verification status
  verificationScore?: number;    // Humanity score (0-100)
  verificationStatus?: 'unverified' | 'pending' | 'verified';
  verifiedHuman?: boolean;       // true if score >= 50

  // Permissions
  isAdmin?: boolean;
  pillarAccess?: string[];      // Access to 7 Pillars
}

export interface UserProfile {
  displayName: string;
  avatarUrl?: string;
  bannerUrl?: string;
  bio?: string;
  reputation: number;
  createdAt?: string;
  updatedAt?: string;
}

// ============================================
// Authentication Types
// ============================================

export interface LoginRequest {
  username: string;
  password: string;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
}

export interface LoginResponse {
  user: User;
  token: string;
  profiles: {
    trueSelf: UserProfile;
    shadow: UserProfile;
  };
  onboardingRequired?: boolean;
}

export interface SwitchModeRequest {
  mode: IdentityMode;
}

export interface SwitchModeResponse {
  success: boolean;
  identity: string;              // New active identity
  mode: IdentityMode;
  token: string;                 // New JWT token
  profile: UserProfile;
}

// ============================================
// Identity Setup Types
// ============================================

export interface IdentitySetupRequest {
  trueSelf: {
    displayName: string;
    bio?: string;
    avatarUrl?: string;
  };
  shadow: {
    useAutoGenerated: boolean;
    customName?: string;         // If not using auto-generated
  };
}

export interface IdentitySetupResponse {
  success: boolean;
  profiles: {
    trueSelf: UserProfile;
    shadow: UserProfile;
  };
  wallets?: {
    trueSelf: string;
    shadow: string;
  };
  dids?: {
    trueSelf: string;
    shadow: string;
  };
}

// ============================================
// Poll Types
// ============================================

export interface Poll {
  id: string;
  title: string;
  description: string;
  status: 'active' | 'closed' | 'draft';
  endDate: string;
  totalVotes: number;
  category: string;
  createdBy: string;             // Identity of creator
  creatorMode: IdentityMode;     // Mode when created
  creatorDisplayName: string;

  // Voting data
  results?: {
    yes: number;
    no: number;
    abstain: number;
  };

  // User's vote (if any)
  userVote?: {
    choice: 'yes' | 'no' | 'abstain';
    reasoning?: string;
    votedAt: string;
  };

  // Governance settings
  quorumRequired?: number;
  approvalThreshold?: number;
}

export interface VoteRequest {
  pollId: string;
  choice: 'yes' | 'no' | 'abstain';
  reasoning?: string;
}

// ============================================
// Session Types
// ============================================

export interface SessionData {
  user: User;
  token: string;
  expiresAt: string;
}

// ============================================
// Error Types
// ============================================

export interface ApiError {
  code: string;
  message: string;
  details?: any;
}

// ============================================
// Utility Types
// ============================================

export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  order?: 'asc' | 'desc';
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}